name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
          - uses: actions/checkout@v2

          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: grc0/docker-openjdk
              flavor: latest=true
              tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}

          - name: Login to image repository
            if: github.ref_type == 'tag'
            uses: docker/login-action@v2
            with:
              registry: docker.io
              username: ${{secrets.DOCKER_HUB_USERNAME}}
              password: ${{secrets.DOCKER_HUB_TOKEN}}

          - name: Build and push
            uses: docker/build-push-action@v3
            with:
              context: .
              file: Dockerfile
              push: ${{ github.ref_type == 'tag' }}
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
